### ISSUE TITLE
Aumentar campo da sigla da senha

### ISSUE THREAD

**Issue by rogeriolino** [novosga/novosga#129]
Aumentar o número máximo de caracteres do campo sigla, permitir siglas com até 3 letras.
##

**Comment by santosmj33** [comment]
Na versão 1,51 ja consegui fazer o numero de caracteres no campo sigla.

**Comment by Alexnunes26** [comment]
como é feita essa alteração pra poder adicionar no máximo 3 letras

**Comment by santosmj33** [comment]
Para alterar quantidade de siglas, consegui uma possibilidade:

1 - Alterei no bco de dados “uni_serv” -> estrutura -> id_sigla ->mudar
para 3 caracteres

2 – Alterei no bco de dados  “atendimentos” -> estrutura -> sigla ->mudar
para 3 caracteres

3 – Alterei no bco de dados  “histórico_atendimentos” -> estrutura ->
sigla_senha ->mudar para 3 caracteres

Depois na pasta “/var/WWW/novosga/src/Novosga/Model/Util”

Utilize um editor de texto que preferir, eu uso o “nano” para editar o
arquivo “Senha.php”

Dentro do arquivo Senha.php procure:

“public function setSigla($sigla)

{

        if (is_string($sigla) && strlen($sigla) == 1) { …..”

e altere para “if (is_string($sigla) && strlen($sigla) == 3) { …..”

Tem que alterar o arquivo “index.html.twig” do /modules/sga/unidade/view,
usando um editor de texto de sua preferência, procure a linha ;

<td classe=”sigla”>

....

...

...

Size=”1” para size=”3”(o mesmo tamanho que colocou no banco de dados)

Maxlength=”1” para Maxlength=”3”(ou o mesmo tamanho que colocou no banco de
dados)

*Obs:  Uma vez modificado para 2 ou mais tamanho do campo, na opção de
configuração do sistema, no campos siglas tem que utilizar 2 ou a
quantidade total de siglas para preencher o campo todo. *



*Para alterar caixa alta de triagem e excluir documento.*

Na pasta /modules/sga/triagem/views

Utilize um editor de texto de sua preferência (no meu caso uso o nano) e
modifique o arquivo índex.html.twig

Excluir a opção de “documento” da linha 16 ate a linha 24.

Salvar e depois

Acrescentar no style.css da pasta /modules/sga/triagem/public/css

#cli_nome {

text-transform: uppercase;}input#cli_nome {     text-transform: uppercase;

}

Para que toda digitação fique em caixa alta.



*                   // guardando historico das 10 ultimas senhas*

Para mostrar somente as 5 ultimas senhas:

Na pasta do painel, vá js, /painel/js

Utilize um editor de texto de preferência e edite o arquivo painel-web.js

Na linha 80 -> altere quantidade 10 para 5


2018-04-25 14:37 GMT-03:00 Alexnunes26 <notifications@github.com>:

**Comment by Alexnunes26** [comment]
Vlw mano
