### ISSUE TITLE
Web: Módulo de agendamento

### ISSUE THREAD

**Issue by rogeriolino** [novosga/novosga#14]
Esse módulo, na verdade será apenas gerencial, apenas para acompanhar os agendamentos. Já que essa funcionalidade implica em alterar outros módulos.

O cliente poderá se cadastrar na fila de atendimento (agendar) em no máximo um dia antes do atendimento previsto. Escolhendo a unidade e o serviço que deseja ser atendido (atendimento normal, não prioritário). Deve ser obrigatório o preenchimento do documento.

Quando o cliente chegar à triagem, deverá apresentar o documento e automaticamente identificará o atendimento agendado para o dia. E atualizará a tabela de agendamento com o número gerado.

Alterar verificação de próximo para procurar também na tabela de agendamento, se existe alguma senha gerada para a data e hora atual. Então chama-la.

A identificação de que o atendimento se trata de um agendamento deverá ser apresentada no Painel, e também para o atendente.

Para facilitar integração com outros sistemas, o cadastro de um novo agendamento deve ser feito por um post em uma determinada URL que retorna um JSON.
##

**Comment by luzanilton** [comment]
Olá senhores. 
Boa noite. 
Houve algum avanço neste módulo de agendamento WEB? 
No aguardo.

**Comment by rogeriolino** [comment]
@luzanilton Não houve.

**Comment by paulocuiaba** [comment]
@rogeriolino Tudo bem? Está planejado esse módulo para a próxima versão? Tem alguma data?

**Comment by alnetosilva** [comment]
Achei super interessante. @rogeriolino acho que o agendamento web deveria ser uma API para consulta de horários disponíveis e uma outra para cadastrar o o agendamento. Uma vez a API pronta é só passar para os sistemas que vão consumir os parâmetros de consulta e de inserção de agendamento!

**Comment by elduke78** [comment]
Buenas tardes, buscando encontre esto:

http://painel.santaluzia.mg.gov.br/novosga/public/agendamento

Si alguno sabe donde esta el desarrollo, estaría bueno que lo compartan.

Saludos

**Comment by anahorn** [comment]
Olá, 
Estamos precisando muito deste módulo de agendamento, estamos interessados inclusive em avaliar como versão paga, algum avanço nesta funcionaldiade?

**Comment by GabrielBN123** [comment]
Olá, como consigo criar um agendamento? ainda não encontrei um lugar específico que mostre como criar, poderia me ajudar @rogeriolino ?

**Comment by EdilvoLima** [comment]
alguem conseguiu instalar a versão 2.1? Não consegui de nenhuma forma instalar a 2.1
