### ISSUE TITLE
[Feature] Configurar serviços a serem exibidos na triagem

### ISSUE THREAD

**Issue by rogeriolino** [novosga/novosga#208]
Poder configurar a exibição dos servidos habilidados para a unidade. Assim facilita a para locais aonde possuem muitos serviços e/ou tem mais de uma triagem.

**Comment by dinartejr** [comment]
Rogério, parabéns pela iniciativa e pelo software. Uso o sistema há uns 6 meses.

Essa sua issue me chamou atenção para um problema que tenho aqui:

O status do serviço nas telas Configuração (Unidade>configuração) e em serviços (Global>Serviços) não deveriam concomitantemente selecionar quais estariam ativos ou não para emissão de senha, redirecionamento e etc?

Quando se desabilita um serviço no modulo serviços(Global>Serviços) eles continuam aparecendo na tela de Configuração (Unidade>configuração) para serem ativados ou não para triagem. 

Esta solução que apresentou desabilita os botões somente na tela de triagem, mas a triagem touch continua mostrando os botoes....

Imagino que a solução ideal seriamos ter no modulo unidades(Global>Unidades) uma forma de selecionar os serviços ativos para a unidade, como acontece no modulo usuários (Global>Usuários).

Desta forma poderíamos cadastrar todos os serviços no global, habilitar os que quisermos em cada  unidade e habilitar novamente os que quisermos para cada usuário. 

Quem sabe poderíamos até redirecionar serviços entre unidades.

Ainda estou me aprofundando no sistema e me desculpe caso não sejam pertinentes.

**Comment by rogeriolino** [comment]
@dinartejr 

São dois status diferentes, o primeiro que define quais serviços aparecerão lá para serem habilitados nas unidades, e o outro status se o serviço está habilitado somente naquela unidade. Realmente o comportamento normal seria desabilitar (sumir) o serviço em todas as unidades caso ele fosse desabilitado globalmente, mas não habilitá-lo nas unidades quando voltar a habilitar globalmente.

Essa separação é muito útil para cenários aonde possuem muitas unidades com serviços distintos, como por exemplo uma Prefeitura que pode ser separada por secretarias. O administrador do sistema, no módulo global de serviços, visualiza todos os serviços independente de unidade, porém o gerente local só visualiza os serviços pertinentes a sua unidade.

Isso poderia ser contornado se cada unidade tivesse um cadastro próprio de serviços, porém dessa forma não daria para compartilhar serviços básicos que podem ser reutilizados em diferentes unidades e depois comparar via relatórios os tempos de cada local.

**Comment by dinartejr** [comment]
Não sabia da diferenciação da visualização entre o administrador e o gerente.

Assim realmente fica bem resolvido.

Obrigado novamente e até logo.
