### ISSUE TITLE
[modules] Remover coluna tipo

### ISSUE THREAD

**Issue by rogeriolino** [novosga/novosga#209]
Não discriminar mais os módulos entre global e local.
##

**Comment by rogeriolino** [comment]
Não existe mais tabela para Módulos, será definido via arquivo de configuração.

**Comment by fielcomunista** [comment]
Estou desenvolvendo dois módulos solicitados aqui. Nem terminei, mas pelo que vejo terei que reescrevê-los para a nova versão! Qual a estrutura (linguagem, frameworks e ...), a melhor forma de fazer isso para a nova versão? O que recomenda? A ideia é disponibilizar estes módulos (Controle de Ausência de Atendentes e Opiniômetro) para a comunidade, se de interesse. Abraços.

**Comment by rogeriolino** [comment]
Os módulos agora são bundles do Symfony 3.4 / 4.0.

Exemplo: https://github.com/novosga/settings-bundle

A diferença do módulo para um bundle normal é que a classe Bundle precisa implementar a interface `Novosga\Module\ModuleInterface`. Um "atalho" é estender a classe `Novosga\Module\Base\BaseModule`.
