### ISSUE TITLE
Mesmo número de guichê

### ISSUE THREAD

**Issue by carlosfilho88** [novosga/novosga#214]
Dois atendentes podem colocar o mesmo número de guichê dentro da mesma unidade.

**Comment by rogeriolino** [comment]
O maior problema será definir uma forma de identificar o guichê do usuário na unidade.

Atualmente a unidade está apenas na sessão, uma maneira de fazer isso é adicionar na tabela ```usu_meta``` a unidade atual do usuário. Na mesma tabela já está sendo salvo o número do guichê. Então só depois daria para fazer essa validação.

**Comment by rogeriolino** [comment]
Faltando adicionar interface para administradar as informações de local e tipo de atendimento dos usuário (módulo usuários). Isso se faz necessário porque caso algum atendente falte ou saia de férias, o administrador do sistema poderá liberar o número do local para que outro atendente possa usar (senão o atendente receberá o erro de local já em uso).

**Comment by somatorio** [comment]
Se eu entendi bem, o problema descrito é que mais de um atendente pode se colocar no mesmo guichê, é isso mesmo?

pra mim soa mais como "it's not a bug, it's a feature"... aqui na prefeitura de Esteio há muitos locais onde há apenas um guichê e multiplas pessoas atendem por ele, pois as suas mesas de trabalho são em um local diferente e elas apenas vão ao guichê propriamente dito para falar com o público a ser atendido e logo voltam a mesa para fazer o atendimento de fato

o ideal seria que fosse possível configurar se o sistema deve aceitar isso ou não

**Comment by rogeriolino** [comment]
@somatorio verdade. Esse travamento tente a gerar mais problema e confusão do que resolver algum problema (se é que é um problema). Estou pensando seriamente em retirar essa restrição.

**Comment by rogeriolino** [comment]
Outra situação é quando o atendimento é separado em salas e cada sala possui mais de um atendente.
