### ISSUE TITLE
Número do guichê sobrescrito ao tentar alterá-lo

### ISSUE THREAD

**Issue by carlosfilho88** [novosga/novosga#217]
O request que é executado a cada 5s /modules/sga.atendimento/ajax_update sobrescreve o valor no modal de alteração do número do guichê.

Quando o atendente tenta alterar o valor, tem que fazê-lo nesse intervalo de 5s, do contrário o valor é substituído com o número atual do guichê que vem do retorno do json.

**Comment by rogeriolino** [comment]
Toda vez que uma modal abre a variável SGA.paused é setada para true. Adicionar condição para verificar essa variável e evitar fazer os request.
