### ISSUE TITLE
Unidade só pertence a um grupo

### ISSUE THREAD

**Issue by carlosfilho88** [novosga/novosga#218]
Esse relacionamento poderia ser de muitos pra muitos: uma unidade poderia estar contida em mais de um grupo.

Por exemplo: a empresa em que trabalho possui várias filiais e dentro de uma mesma unidade há mais de uma agência de atendimento (em locais distintos do prédio).

Ou seja, atualmente, cada grupo só está associado a uma unidade, sendo que, seria interessante mais grupos fazerem parte da unidade, visto que há revezamento de turnos e de postos dos funcionários entre as agências de atendimento.

**Comment by rogeriolino** [comment]
Um grupo pode ter mais de uma unidade, mas a unidade só pode pertencer a um grupo.

Resumindo, a unidade deve estar sempre associada ao grupo folha, que só tem uma unidade, mas um grupo superior possui todas as unidades dos grupos abaixo.
