### ISSUE TITLE
Melhorar esquema de update

### ISSUE THREAD

**Issue by carlosfilho88** [novosga/novosga#219]
Rogério, seria legal sobrescrever apenas os arquivos alterados, não? E controlar minor updates de major updates. Tipo, um major update alteraria o projeto todo (como atualmente) e os minor updates só os arquivos que foram alterados entre os releases.

Além disso, seria mais legal ainda se a taks de atualizar baixasse o arquivo pro servidor, a descompactasse e automaticamente sobrescrevesse os arquivos. Evitaria o trabalho de devs que não tem acesso ao bash de fazer esse serviço.
##

**Comment by rogeriolino** [comment]
Criar atualizações a partir de diff geraria uma complexidade muito grande a cada release. E pelas questões de alterações feitas localmente, é recomentado sempre fazer utilizando os arquivos de configuração (config/app.php por exemplo), que não são distribuidos junto ao sistema e com isso não são sobrescrito.

Já sobre pré-instalador, já tenho alguma coisa pronta mas ainda não pretendo liberar isso. Talvez em alguma versão futura.
