### ISSUE TITLE
Fatal error when accesing novosga root URL.

### ISSUE THREAD

**Issue by charlyR** [novosga/novosga#220]
When accessing the root URL of novosga without specifying the /login i get the following error:
Example: http://novoga.sample.com or http://novoga.sample.com/

Fatal error: Uncaught exception 'Slim\Exception\Stop' in /var/www/novosga/vendor/slim/slim/Slim/Slim.php:1022 Stack trace: #0 /var/www/novosga/vendor/slim/slim/Slim/Slim.php(1042): Slim\Slim->stop() #1 /var/www/novosga/vendor/slim/slim/Slim/Slim.php(1105): Slim\Slim->halt(302) #2 /var/www/novosga/vendor/slim/slim/Slim/Slim.php(1117): Slim\Slim->redirect('/login', 302) #3 /var/www/novosga/src/Novosga/Slim/AuthMiddleware.php(64): Slim\Slim->redirectTo('login') #4 /var/www/novosga/vendor/slim/slim/Slim/Slim.php(1302): Novosga\Slim\AuthMiddleware->call() #5 /var/www/novosga/public/index.php(135): Slim\Slim->run() #6 {main} thrown in /var/www/novosga/vendor/slim/slim/Slim/Slim.php on line 1022

**Comment by rogeriolino** [comment]
@charlyR try putting rewritebase

    RewriteBase /

**Comment by charlyR** [comment]
Not working, If i use http://novoga.sample.com/login everything works fine.

My Apache novosga.conf file

<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot /var/www/novosga/public
    ServerName 172.19.203.119
    ErrorLog logs/sga-error_log
    CustomLog logs/sga-access_log common
#    RewriteLog logs/sga-rewrite
#    RewriteLogLevel 1

    <Directory "/var/www/novosga">
#        DirectoryIndex index.php index.html
#        Options Indexes MultiViews FollowSymLinks
        AllowOverride All
#        Order allow,deny
#        Allow from all
    </Directory>
</VirtualHost>

**Comment by carlosfilho88** [comment]
@charlyR please check if your mod_rewrite is enabled:

```
ls /etc/apache2/mods-enable
```

And enable it if you can't see *rewrite.load* file:

```
sudo a2enmod rewrite
```

Also, check your */var/www/novosga/public/.htaccess* file:

```
RewriteEngine On
# modules resources
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^/modules/(\w+)\.(\w+)/resources/(.+)$ resources.php [QSA,L]
# app rewrite
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

**Comment by charlyR** [comment]
mod_rewrite is enabled. 
Also de .htaccess file looks the same. 
I am using the latest sga version (1.4).
The problem appears only when you access the root URL BEFORE login.
http://sga_url not working
http://sga_url/ not working
http://sga_url/login works fine. After logon if i go to the root URL i am redirected to /home wich is correct.

**Comment by carlosfilho88** [comment]
@charlyR could you paste your VirtualHost config?

**Comment by charlyR** [comment]
I already paste it above. 
novosga.conf 
```
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot /var/www/novosga/public
    ServerName 172.19.203.119
    ErrorLog logs/sga-error_log
    CustomLog logs/sga-access_log common
#    RewriteLog logs/sga-rewrite
#    RewriteLogLevel 1

    <Directory "/var/www/novosga">
#        DirectoryIndex index.php index.html
#        Options Indexes MultiViews FollowSymLinks
        AllowOverride All
#        Order allow,deny
#        Allow from all
    </Directory>
</VirtualHost>
```

**Comment by carlosfilho88** [comment]
@charlyR just to clarify, ok? Do you have other VirtualHosts in this server? Can you test a different ServerName config? 

First, edit your /etc/hosts file and add a new line
127.0.0.1 novosga.localhost

And then, change your ServerName to novosga.localhost

**Comment by charlyR** [comment]
I don´t have any other virtualhost, i am testing the 1.4 version before passing it to production enviroment. I made the changes you suggested with no luck.

I think it´s not apache configuration related, i have change the novosga.conf to point to the old version (1.2) and all works fine. The problem appears with the new version of novosga (1.4) and the way it is handling the first redirect to /login.

```
<VirtualHost *:80>
    ServerAdmin webmaster@dummy-host.example.com
    DocumentRoot /var/www/novosga.old/public
    ServerName 172.19.203.119
    ErrorLog logs/sga.trp.com.ar-error_log
    CustomLog logs/sga.trp.com.ar-access_log common
#    RewriteLog logs/sga.trp.com.ar-rewrite
#    RewriteLogLevel 1

    <Directory "/var/www/novosga.old">
#       DirectoryIndex index.php index.html
#       Options Indexes MultiViews FollowSymLinks
        AllowOverride All
#       Order allow,deny
#       Allow from all
    </Directory>
</VirtualHost>
```

**Comment by carlosfilho88** [comment]
@charlyR try change your .htaccess file on /public directory:

From:
`RewriteRule ^modules/(\w+)\.(\w+)/resources/(.+)$ resources.php [QSA,L]`

To:
`RewriteRule ^/modules/(\w+)\.(\w+)/resources/(.+)$ resources.php [QSA,L]`

Note, there's a **/** before 'modules'.

**Comment by charlyR** [comment]
Changed... still the same error on Slim.

**Comment by carlosfilho88** [comment]
@charlyR please change your file:

``` /var/www/novosga/src/Novosga/Slim/AuthMiddleware.php ``` **line 64**

from 

``` $this->app->redirectTo('login'); ```

to

``` $app = \Slim\Slim::getInstance();
return $app->response()->redirect($app->urlFor('login')); ```

should work (:

**Comment by rogeriolino** [comment]
Instead of call Slim::getInstance() try this:

    $this->app->response()->redirect($this->app->urlFor('login'));

**Comment by charlyR** [comment]
Problem solved! Thanks!
