### ISSUE TITLE
Ordenação da fila de atendimento

### ISSUE THREAD

**Issue by carlosfilho88** [novosga/novosga#222]
O cálculo poderia ser generalizado para uma fórmula (ou para um select onde houvesse essa opção), na qual o admin poderia atender proporcionalmente a fila.

Normalmente o atendimento no Brasil se dá pela proporção de 2 convencionais para 1 prioritário, sendo que o prioritário é adicionado ao topo da fila quando há somente atendimentos convencionais.

**Comment by rogeriolino** [comment]
A ordenação pode ser customizada de acordo com a necessidade de cada lugar.

https://github.com/novosga/novosga/blob/b8bd852887c16b82f7d64a0986bcc501ec659f61/src/Novosga/Service/FilaService.php#L17-L34

E pode ser sobrescrito no arquivo de configuração ```config/app.php```

https://github.com/novosga/novosga/blob/b8bd852887c16b82f7d64a0986bcc501ec659f61/src/Novosga/Service/FilaService.php#L142-L148

**Comment by cleiton-ti** [comment]
Poderia me mandar o código completo por favor, porque fiz e deu erro

**Comment by cleiton-ti** [comment]
Gostaria se possível.
O sistema ordenasse da seguinte forma:
Se eu tirei 5 senhas normais e logo tirei a 6 como preferencial, o sistema me colocasse a 6 como primeiro lugar
