### ISSUE TITLE
Tradução de módulos

### ISSUE THREAD

**Issue by ptopenweb** [novosga/novosga#224]
Como se pode traduzir os módulos e as suas descrições?

Diretamente na base de dados é possível (tabela módulos).
Não deveria ser possível haver tradução dos módulos também?
##

**Comment by rogeriolino** [comment]
Hoje a tradução dos módulos está no arquivo principal (default.mo) e durante a instalação é salvo no banco os textos já traduzidos (os textos ficam no manifest.json do módulo).

O correto é cada módulo possuir sua pasta locale com as suas respectivas traduções, e separar as traduções em domínios:

https://github.com/novosga/novosga/blob/master/src/Novosga/Util/I18n.php#L88

https://github.com/novosga/novosga/blob/master/public/index.php#L111-L112

Porém o twig ainda não possui suporte a múltiplos domínios (dgettext). Mas existe um pull request para essa funcionalidade (ainda em aberto): https://github.com/twigphp/Twig-extensions/pull/117

Quando for adicionado esse suporte ao twig será necessário criar os locales para cada módulo e alterar os arquivos .twig para chamar a internacionalização especificando o domínio.

**Comment by rogeriolino** [comment]
Na versão 2.0 os módulos serão bundles do Symfony3 então cada bundle (módulo) terá o seu arquivo de tradução.

**Comment by JoranFreire** [comment]
Rogério,

qual a possibilidade de criar um módulo webservice para que outras aplicações possam consumir informando o atendimento que está sendo feito? Pergunto isso para que possamos viabilizar uma integração do SGA com qualquer sistema fim de órgãos ou empresas.

Att.,

**Comment by rogeriolino** [comment]
@JoranFreire na versão 2.0 a API será melhorada para prover mais informações.
