### ISSUE TITLE
API ERROR: Use of undefined constant NOVOSGA_INSTALLED - assumed 'NOVOSGA_INSTALLED'

### ISSUE THREAD

**Issue by charlyR** [novosga/novosga#231]
Use of undefined constant NOVOSGA_INSTALLED - assumed 'NOVOSGA_INSTALLED' when submitting a new ticket to novosga via api from triagem-touch.

Server: Novosga 1.4.0

**Comment by rogeriolino** [comment]
@charlyR can you test it too?

**Comment by charlyR** [comment]
Tested: Install process, triagem-touch printing, sga web app. 
Everything is working fine.
