### ISSUE TITLE
Remover situação do atendimento (Encerrado e codificado)

### ISSUE THREAD

**Issue by rogeriolino** [novosga/novosga#243]
Remover o status `AtendimentoService::ATENDIMENTO_ENCERRADO_CODIFICADO` e passar utilizar o `AtendimentoService::ATENDIMENTO_ENCERRADO` como situação final (atendimento concluído com sucesso).

Essa situação vem do o SGA Livre, aonde a página de atendimento era toda recarregada e então havia essa necessidade de manter a página na listagem dos serviços executados.

OBS: Adicionar ao script SQL de upgrade o UPDATE para trocar o status 8 para 4.
##

**Comment by rogeriolino** [comment]
Alterada coluna tipo de `int` para `string`.

**Comment by fielcomunista** [comment]
@rogeriolino essa mudança de tipo da coluna causará impacto na migração do banco atual? Haverá um script de conversão integrado ou o processo será mantido manual? Pergunto por questões de conhecimentos aos quais nem todos estão familiarizados (mesmo que simples).

**Comment by rogeriolino** [comment]
@fielcomunista essa versão irá quebrar a compatibilidade com as versões anteriores. 

Como estou focado no desenvolvimento da nova versão não fiz um script de migração. Devo trabalhar nisso só depois do lançamento da v2.0 mesmo, ou torcer para que a comunidade ajude nessa tarefa.

Mas enfim, inicialmente não haverá upgrade direto de uma versão para outra. Terá que fazer uma nova instalação e migrar os dados.

**Comment by fielcomunista** [comment]
Não prometo, mas como terei que fazer a migração em algum momento futuro não custa disponibilizar o que eu fizer para a comunidade. Obrigado.
