### ISSUE TITLE
Pesquisa por usuários com mais de uma página de resposta

### ISSUE THREAD

**Issue by paulocuiaba** [novosga/novosga#248]
Olá, 

Quando pesquisando um usuário (Novo SGA 1.1.3 > GLOBAL > Usuários ) e existem muitos resultados ...

![image](https://cloud.githubusercontent.com/assets/6816524/8732723/3e5c1b56-2bcd-11e5-97fa-c13fb7daa140.png)

e clicamos na segunda página ou na seta para ir ao final, o sistema retorna a listagem de usuários, não continuando a pesquisa. 

![image](https://cloud.githubusercontent.com/assets/6816524/8732729/4ad050f0-2bcd-11e5-8e96-6bb90a8b626b.png)

Não é um caso tão importante, pois geralmente o resultado não será muito grande, a não ser que haja muitas "marias".

Obrigado!
##

**Comment by rogeriolino** [comment]
Para versão 2.0.0 vou refazer as paginações.
