### ISSUE TITLE
Instalação Novosga 1.5 erro

### ISSUE THREAD

**Issue by SoaresSergio** [novosga/novosga#252]
Intalação Novo Sga 1.5 devolve seguinte erro:

An exception occurred while executing 'INSERT INTO locais (nome) VALUES (?)' with params ["Balc\u00e3o"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Balcão' for key 'local_serv_nm'

http://localhost/novosga/public/install/5An exception occurred while executing 'INSERT INTO locais (nome) VALUES (?)' with params ["Balc\u00e3o"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Balcão' for key 'local_serv_nm'

http://localhost/novosga/public/install/5

Agradeço desde já a  ajuda para instalar o Novo Sga.

**Comment by rogeriolino** [comment]
Você tentou instalar sobre alguma versão anterior?

**Comment by SoaresSergio** [comment]
Desde já quero agradecer a atenção dispensada.
Estou a instalar pela primeira vez no win 7.
Obrigado.

**Comment by rogeriolino** [comment]
Crie um novo banco e tente instalar nele novamente.

**Comment by SoaresSergio** [comment]
Ao instalar de novo devolve o seguinte: "erro ao instalar o SGA"

**Comment by SoaresSergio** [comment]
Continuo sem conseguir instalar Novo Sga 1.5 no Windows.
Ja tentei em varias versões do windows e em maquinas diferentes, utilizei tambem a instalação com o composer, mas obtenho sempre o mesmo erro:
An exception occurred while executing 'INSERT INTO locais (nome) VALUES (?)' with params ["Balc\u00e3o"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Balcão' for key 'local_serv_nm'

http://localhost/novosga/public/install/5An exception occurred while executing 'INSERT INTO locais (nome) VALUES (?)' with params ["Balc\u00e3o"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Balcão' for key 'local_serv_nm'

http://localhost/novosga/public/install/5

Agradecia ajuda para este problema, obrigado.

**Comment by rogeriolino** [comment]
O problema está na tradução para o Português de Portugal. Ambas palavras Mesa e Guichê foram traduzidas para Balcão.

Você pode contornar isso alterando o idioma do seu navegador, acertar o arquivo de tradução `locales/pt_PT/LC_MESSAGES/default.po` via o PoEdit, ou alterar o arquivo `modules\sga\locais\DataFixture.php` removendo uma das linhas (Guicê ou Mesa).

**Comment by SoaresSergio** [comment]
Obrigado pela sua disponibilidade.
Vou experimentar.

Grande Abraço

Sérgio Soares

No dia 1 de setembro de 2015 às 15:49, Rogério Alencar Lino Filho <
notifications@github.com> escreveu:
