### ISSUE TITLE
Restrição por hierarquia de acesso/serviços selecionados

### ISSUE THREAD

**Issue by matheusnevestipmsl** [novosga/novosga#260]
Restringir a possibilidade de acesso à informações de usuários ou serviços não selecionados para um usuário.

Exemplo: Um usuário comum, com acesso ao módulo de usuários não deveria ter a possibilidade de cadastrar, alterar ou excluir administradores e sim apenas usuários de hierarquia mais baixa.

No módulo monitor o usuário deveria ver apenas as filas dos serviços marcados para ele e não as demais.

**Comment by rogeriolino** [comment]
A partir da versão 2.0 o módulo de usuários exibe apenas os usuário da unidade atual.

E criado coluna "admin" para diferenciar usuário administrador dos demais.
