### ISSUE TITLE
Seleção do serviço por parte do atendente

### ISSUE THREAD

**Issue by matheusnevestipmsl** [novosga/novosga#264]
Caso o atendente atenda um serviço específico porém no período sem atendimentos atender outro serviço, ele poderia ter a possibilidade de selecioná-lo (caso cadastrado no usuário) da mesma forma que a Triagem.
Exemplo: O Atendente é exclusivo do serviço A, porém não há nenhuma senha esperando esse serviço, ele então seleciona o serviço B somente até possuir uma senha novamente no serviço A.

**Comment by rogeriolino** [comment]
A configuração de qual serviço o atendente deve atender deve ficar a cargo do coordenador/gerente.

Tal funcionalidade abre margem para o atendente priorizar um serviço em detrimento a outros que julgar mais trabalhosos.

Na versão 2.0 a configuração dos serviços que os usuários atendem fica no módulo de configuração da unidade.
