### ISSUE TITLE
painel FX não funciona com java 7  nem com java 8

### ISSUE THREAD

**Issue by Montezi** [novosga/novosga#266]
Boa tarde! Customizamos o novosga para utilização, porém a versão que nós utilizamos não há como utilizar o painel web e no momento não temos como realizar o upgrade da aplicação por conta das alterações realizadas no BD. 
O painel FX cliente estava funcionando bem no windows 7 com jdk 7, de repente parou de funcionar e não traz mais as unidades. Realizando testes descobrimos que funciona com o jdk 8 no windows 7, porém fica com a formatação maior que a do monitor. 
Realizando testes no Ubuntu 14.04, acontece a mesma coisa com a jdk 7 e com a jdk 8 simplesmente não abre, fica uma tela branca e no terminal aparece a mensagem :"Grave:Erro ao registrar painel". 
Há alguma versão de jdk específica? Preciso resolver este problema, pois somente na segunda versão poderemos utilizar o painel web.

**Comment by rogeriolino** [comment]
O PainelFX foi descontinuado, assim como a versão 0.*.

O que é estranho é o sistema parar de funcionar do nada. Tente levantar o que foi alterado no ambiente.
