### ISSUE TITLE
atendimentos table auto-number reset

### ISSUE THREAD

**Issue by charlyR** [novosga/novosga#269]
Sometimes the table auto-numbering resets to 1, and get a confict with the historico tables.
Change the algoritm to reset numbering every day to prevent this failure.

**Comment by rogeriolino** [comment]
This is explained in the issue #155. When using MySQL and InnoDB the sequential column is reseted when MySQL server restart/reboot.

Try changing the engine to MyISAM.

**Comment by rogeriolino** [comment]
@charlyR can you confirm me if MyISAM fixes your issue?

**Comment by charlyR** [comment]
As a workaround i do an ALTER TABLE for the next available number and then
update table id and references in atendimentos, atend_codif.
I Will try  the myisam solution on test envrioment

**Comment by charlyR** [comment]
Can you please test this to fix InnoDB?

1. Create autonumberfix.sql
SELECT @inc_value := MAX(id) +1 FROM (SELECT max(id) as id FROM atendimentos UNION SELECT max(id) as id FROM historico_atendimentos) AS Maximos;
SET @alter_query = CONCAT('ALTER TABLE atendimentos AUTO_INCREMENT=',@inc_value); 
PREPARE alter_query FROM @alter_query; 
EXECUTE alter_query; 
DEALLOCATE PREPARE alter_query; 

2. Put autonumberfix.sql file in /etc/my.cnf.d/

3. Edit  /etc/my.cnf
Add to
[mysqld] 
init-file=/etc/my.cnf.d/autonumberfix.sql

Thanks.

**Comment by rogeriolino** [comment]
I've already changed the table engine to MyISAM on newest NovoSGA versions.

This workaround isn't necessary.

**Comment by charlyR** [comment]
OK. Changed engine to MyISAM on tables solves the problem.
Thanks!
