### ISSUE TITLE
A confirmação da senha deve ser informada

### ISSUE THREAD

**Issue by ystallonne** [novosga/novosga#271]
Durante a instalação, não é possível prosseguir no passo 5. A mensagem de erro "A confirmação da senha deve ser informada." não deixa continuar, apesar de, obviamente, estarem todos os campos devidamente preenchidos.

**Comment by rogeriolino** [comment]
Qual versão você tentou instalar?

**Comment by GersonCarmo** [comment]
Estou com o mesmo problema.  
# uname -a
Linux SGAServer 4.4.0-79-generic #100~14.04.1-Ubuntu SMP Fri May 19 18:36:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#  php composer.phar create-project novosga/novosga /var/www/html/novosga "1.*"
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing novosga/novosga (v1.5.1)
  - Installing novosga/novosga (v1.5.1): Downloading (100%)

**Comment by GersonCarmo** [comment]
Resolvido. refiz os passos de instalação, criei um novo banco e novo usuário e agora foi sem falhas
