### ISSUE TITLE
Erro Sequencia de Senhas Convencional e Prioritaria

### ISSUE THREAD

**Issue by paulocuiaba** [novosga/novosga#279]
Bom dia,

Notamos que o sistema está apresentando uma inconsistência na sequência de senhas. Conforme pode ser observado nas telas em anexo, uma senha prioritária (F19) está ficando depois de uma senha normal (F20).

![erro sga 01](https://cloud.githubusercontent.com/assets/6816524/18638502/64438c2a-7e5e-11e6-8729-a51be64ca778.png)

O sistema está configurado com as informações padrões.

![erro sga 02](https://cloud.githubusercontent.com/assets/6816524/18638501/64421f8e-7e5e-11e6-95c4-e5437e0f4c31.PNG)

Como pode ser visto isto só acontece por alguns segundos, creio que após 1 minuto regulariza, como na segunda imagem, mas ocorre que nesse intervalo pode chamar e ai acaba que chama primeiramente a senha normal em vez da prioritária, mesmo a normal sendo emitida depois.

**Comment by rogeriolino** [comment]
Comportamento normal devido ao balanceamento entre a prioridade e o tempo de chegada:

https://github.com/novosga/novosga/blob/v1.5.1/src/Novosga/Service/FilaService.php#L22

**Comment by rafael-neri** [comment]
Eu passei por um problema parecido onde as senhas de prioridade sempre iam para o final da fila enquanto as senhas normais passavam na frente das prioridades. Mesmo após 1 minuto a fila continuava da mesma forma.

Dei uma vasculhada no código, resolvi o meu problema e submeti a correção para o repositório do SGA.

Aqui vai a parte que eu modifiquei:
https://github.com/novosga/novosga/pull/282/commits/106f66af07ac536e338f9f5c6fcc03599e289444

**Comment by djhanlj** [comment]
@rafael-neri estava com o mesmo problema, sua solução resolveu pra mim, mas essa alteração afeta alguma outra funcionalidade?

**Comment by rafael-neri** [comment]
Olá @djhanlj !!
Eu descobri que não precisa fazer mais essa alteração.
Bastar criar um arquivo de configuração.

```php
<?php
// config/app.php
return [
    'queue' => [
        'ordering' => [
            [
                'exp'   => 'p.peso',
                'order' => 'DESC',
            ],
            [
                'exp'   => 'e.numeroSenha',
                'order' => 'ASC',
            ]
        ]
    ]
];
```

**Comment by djhanlj** [comment]
@rafael-neri mas isso funcionará para versão v1.5.0, é a que estou utilizando no momento.

**Comment by rafael-neri** [comment]
@djhanlj essa funcionalidade está disponível a muito tempo, eu que não conhecia na época.
Acredito que funcionará.

**Comment by emersonsimoes** [comment]
onde eu coloco esse arquivo de configuração?

**Comment by rafael-neri** [comment]
@emersonsimoes dentro da pasta config.
Basta criar o arquivo app.php dentro dessa pasta com o código que eu passei.

**Comment by emersonsimoes** [comment]
Show deu certo aqui comigo... foi isso mesmo vlw @rafael-neri

**Comment by ScharlesSouza** [comment]
Boa tarde,
tive o mesmo problema das senhas normais passar na frente das senhas prioridade.
Fui olhar como funciona a fila do novoGSA 1.5.0 e esta tudo certo com "time wait". 
Verifiquei a hora do servidor e do postgres, estava tudo certo.
O que ocorria, no meu caso, é que o timezone do php.ini estava em horario de verão (BRT -02).
para verificar utilizei um aqruivo php no servidor apache, com o seguinte codigo:
<?php
echo(date('d/m/Y H:i:s e T'));
?>
