### ISSUE TITLE
Senhas normais passam na frente de prioridade

### ISSUE THREAD

**Issue by rafael-neri** [novosga/novosga#281]
O que ocorre é que as senhas prioritárias sempre estão indo para o final da fila e a senhas normais passam na frente dos prioritários.

**Comment by rogeriolino** [comment]
@rafael-neri ,

A ordenação pelo tempo de espera em primeiro é justamente para evitar problemas de uma senha prioritária ir para frente da fila logo ao chegar, passando pessoas que já estão esperando por um longo tempo. Então é feito um balanciamento do tempo de espera com o peso da prioridade. Inicialmente o prioritário irá aparecer no final da fila mas conforme passar o tempo ele irá para a frente dos convencionais.

De qualquer maneira, caso você não queira esse comportamento na sua instalação você pode sobrescrever essa ordem via arquivo de configuração. Conforme dá para ver em https://github.com/novosga/novosga/blob/master/src/Novosga/Service/FilaService.php#L149:

```
<?php
// config/app.php
return [
    'queue' => [
        'ordering' => [
            [
                'exp'   => 'p.peso',
                'order' => 'DESC',
            ],
            [
                'exp'   => 'e.numeroSenha',
                'order' => 'ASC',
            ]
        ]
    ]
];
```

O sistema só irá utilizar essa configuração padrão de ordem caso não tenha essa configuração no arquivo `config/app.php`.


*OBS:* Ao ordenar pela prioridade e pelo número da senha já não precisará ordenar pelo tempo de espera.

**Comment by rafael-neri** [comment]
Até ai tudo bem mas o problema é justamente que os que tiram senhas normais após o prioritario entra na frente dele. Isso é um comportamento altamente indesejado, afinal qualquer senha normal entra na frente da prioridade.

**Comment by rogeriolino** [comment]
Provavelmente o problema do convencional estar passando na frente é porque há uma diferença de horário entre o seu servidor PHP e o banco de dados.

**Comment by rafael-neri** [comment]
E só pra complementar, prioritário tem que ser atendido primeiro.
O significado de prioritário é esse.

**Comment by rogeriolino** [comment]
@rafael-neri dê uma olhada nos horário.

**Comment by rafael-neri** [comment]
@rogeriolino os horarios estão sincronizados.

**Comment by rafael-neri** [comment]
Eu sei que nem todas as instituições são obrigadas a oferecer atendimento prioritario mas tanto as que são obrigadas como as que não são e fazem esse tipo de atendimento, devem ficar atento ao que é apresentando na lei relacionada.

Segue abaixo uma pequena explanação encontrada no site do "Conselho Nacional do Ministério Público":

> O atendimento prioritário de que trata a Lei nº 10.048/00 consiste em serviços individualizados que assegurem tratamento diferenciado e atendimento imediato.

> O tratamento diferenciado está especificado no Decreto nº 5.298/04, de maneira não exaustiva, incluindo, por exemplo, a disponibilidade de espaços e instalações acessíveis.

> O Decreto nº 5.296/04 estabelece que o atendimento imediato é aquele prestado
aos seus beneficiários, antes de qualquer outra pessoa, depois de concluído o
atendimento que estiver em andamento.

http://www.cnmp.mp.br/portal/images/guiaOrientaçaoAtendimentoPrioritario_2014_Rebecca.pdf
.

**Comment by rogeriolino** [comment]
> Até ai tudo bem mas o problema é justamente que os que tiram senhas normais após o prioritario entra na frente dele. Isso é um comportamento altamente indesejado, afinal qualquer senha normal entra na frente da prioridade.

A fórmula é: (peso da prioridade + 1) * tempo de espera.

Levando em consideração que o peso da senha prioritária é 1 e da convencional é 0, e que um atendimento normal chegou 1 segundo após o prioritário, teremos:

- Primeiro a chegar, prioritória, peso 1, espera 1, logo: (1 + 1) * 1 = 2
- Segundo a chegar, normal, peso 0, espera 0, logo: (0 + 1) * 0 = 0

Ordenando de maneira decrescente, o primeiro a ser atendido será o prioritário.

Já sobre a orientação do CNMP, o termo imediato não é aplicável na prática por questões óbvias. Por exemplo, em uma unidade aonde possui 1 guichê, ao chegarem 3 atendimentos prioritários, 1 terá que esperar mais do 1 atendimento em andamento. E o mesmo acaba entrando em confronto com a lei de tempo máximo de espera para ser atendido.

Por fim, o sistema é configurável, se é uma necessidade sua que qualquer atendimento prioritário vá para o início da fila mesmo que tenha pessoas esperando a 40 minutos (ou qualquer outro tempo de espera que estoure o aceitável) basta fazer como mostrei anteriormente e criar o arquivo de configuração.

**Comment by rogeriolino** [comment]
@rafael-neri de qualquer forma, gostaria de agradecer sua atitude de contribuir para projetos opensource. Parabéns.

**Comment by rafael-neri** [comment]
> A fórmula é: (peso da prioridade + 1) * tempo de espera:

Eu entendi a formula mas por algum motivo não está funcionando como deveria, por isso recebi muitas reclamações.

> Por fim, o sistema é configurável, se é uma necessidade sua que qualquer atendimento prioritário vá para o início da fila mesmo que tenha pessoas esperando a 40 minutos (ou qualquer outro tempo de espera que estoure o aceitável) basta fazer como mostrei anteriormente e criar o arquivo de configuração.

Por mim tudo, sei como corrigir mas sei também que muitos não saberão e talvez fosse melhor que pelo menos essa configuração estivesse disponível na administração do sistema. É uma sugestão.

**Comment by rafael-neri** [comment]
> @rafael-neri de qualquer forma, gostaria de agradecer sua atitude de contribuir para projetos opensource. Parabéns.

Eu que agradeço pelo belo trabalho e acredito que em breve estarei de volta como mais algumas contribuições.

**Comment by rogeriolino** [comment]
Concordo que deveria ter uma interface para poder configurar isso. Seria muito bom.

Quando comentei dos horários com você é porque já tive problema justamente com isso, e como a aplicação estava em um servidor e o banco de dados em outro, tinha diferença de horário. Então o tempo de espera dava negativo e a prioridade ficava sempre por último.

No repositório tem um branch v2.0 que estou trabalhando ainda, uma versão reformulada e utilizando o framework Symfony3. Se tiver interesse em ajudar, dê uma olhada nesse branch.

Abraço!
