### ISSUE TITLE
Troca de unidade com atendimento em andamento.

### ISSUE THREAD

**Issue by higorcouto** [novosga/novosga#283]
Existe um erro no sga, caso o usuário atenda em mais de uma unidade e troque de unidade com um atendimento em andamento ocasiona um embaralhamento. Podendo atualizar a senha com os dados da outra unidade, e assim quando for necessário reiniciar as senhas também da erro pois a senha é referencia em duas unidades.

Resolvi o erro proibindo a troca de unidade caso aja um atendimento já em andamento.

**Comment by rogeriolino** [comment]
Obrigado por relatar o problema @higorcouto 

Penso em adicionar a condição da unidade atual na hora de pegar o atendimento em andamento. Assim evitaria esse problema.

Att.
