### ISSUE TITLE
V2 Post installation - Create or alter tables

### ISSUE THREAD

**Issue by charlyR** [novosga/novosga#287]
1. After installing Novosga 2.00 and complete the database parameters, if the database is 1.5 it is not upgraded; if a new database is created (novosga.v2 for example) no tables are created.

Process:
```
git clone -b v2.0 https://github_user%40domain:user_passwd@github.com/novosga/novosga novosga-2.00
cd novosga-2.00
composer install
complete parameters (database access, mail server, secret)
cd ..
chown -R apache:apache novosga-2.00
```
Navigate to the novosga site via webbrowser and the login page appears, with no configuration or upgrade options.

**Comment by rogeriolino** [comment]
I'll not develop upgrade feature to 2.0 version.  To upgrade previous version of NovoSGA I'll create (maybe) another project. And to future releases I'll use doctrine migrations.

As the v2.0 is over Symfony framework, the installation occur via console after Composer install. No more webpage to install/upgrade (for a while).

**Comment by rogeriolino** [comment]
>if a new database is created (novosga.v2 for example) no tables are created.

Creating a new database before run `composer install` doesn't create tables?

Try run this command `bin/console doctrine:schema:update --dump-sql` and look the output.

**Comment by rogeriolino** [comment]
To create tables:

    bin/console doctrine:schema:create

To install demo data:

    bin/console doctrine:fixtures:load

Users:

- admin: 123456
- rogerio: 123456

**Comment by charlyR** [comment]
That´s right. Creating new database before run composer install doesn't create tables.
Manually running the commands after install, works fine.
```
bin/console doctrine:schema:create
bin/console doctrine:fixtures:load
```
