### ISSUE TITLE
Improvement parameters.yml NovoSGA v2

### ISSUE THREAD

**Issue by charlyR** [novosga/novosga#288]
1. Move `locale` from `config.yml` to `parameters.yml `to change the default language.
2. Change default database name in `parameters.yml.dist` to something like novosga-v2
3. Add auto language detection support, also add a parameter to enable or not auto detection.

**Comment by rogeriolino** [comment]
Added `locale` to `parameters.yml.dist`.

The database name and locale parameters will keep free for user to type.

ps: Incenteev/ParameterHandler not provide dynamic parameter value, only static value.
