### ISSUE TITLE
Duplicidade de Senhas

### ISSUE THREAD

**Issue by paulocuiaba** [novosga/novosga#290]
Estamos tendo alguns problemas que está ocasionando na duplicação da mesma senha em um mesmo serviço. Geralmente ocorre quando há muitas pessoas para serem atendidas. Não sei se seria um problema na aplicação, na rede, no banco de dados ou ainda no computador que está emitindo a senha por ser um equipamento antigo. Alguém já passou por este tipo de problema? Podem me dar alguma luz?
obrigado!

Na tela em anexo está a mesma senha A697 2x. Acontece até de aparecer 4x a mesma senha. Consigo cancelar e some somente a que foi clicada pra cancelar, mas é um problema que não deveria acontecer. Não são impressas senhas com mesmo número. 

![duplicidade senhas](https://cloud.githubusercontent.com/assets/6816524/22482112/5006b35e-e7d6-11e6-80fd-f1bc69a48272.PNG)

**Comment by rogeriolino** [comment]
Qual versão do sistema?

**Comment by paulocuiaba** [comment]
Versão 1.5.1. Estranho que consigo cancelar essas duplicidades. Acontece somente quando há um fluxo muito grande de contribuintes. Acontece te aparecer mais de 3 senhas iguais.

**Comment by thyagomn** [comment]
@paulocuiaba as senhas duplicadas foram emitidas pelo mesmo usuário ou usuários diferentes emitiram a mesma senha? Se forem senhas emitidas por usuários distintos, é um problema que creio que o @rogeriolino já esteja resolvendo para a versão 2 mas ainda existe na versão 1.5.x. Mas para a sua sorte, consegui criar uma maneira de evitar isso, verifique esse link do forum:http://forum.novosga.org/discussion/comment/1789/#Comment_1789 talvez resolva seu problema.

**Comment by paulocuiaba** [comment]
Obrigado @thyagomn pela informação. Na verdade era no terminal de autoatendimento (triagem touch), então seria sim realizado pelo mesmo usuário e não por diferentes. Somente ocorre quando há um grande fluxo na loja de atendimento. Irei aplicar sua solução e ver se resolve o problema. Abraços!

**Comment by thyagomn** [comment]
@paulocuiaba aqui nós temos um balcão de triagem, mas acho que essa solução talvez resolva o seu problema. 
Mas caso você tenha desenvolvido a triagem touch ou mesmo baixado, recomendo colocar um timeout para desabilitar o botão de emissão de senha por alguns segundos (caso você ainda não tenha feito isso). Não me lembro se o módulo de triagem touch disponibilizado faz isso...

**Comment by rogeriolino** [comment]
@thyagomn obrigado pela contribuição.

A boa notícia é que na versão 2.0 esse problema estará de vez corrigido (assim espero). A má notícia é que não terá mais versão 1.x, ou seja uma nova versão para corrigir esse problema a partir da versão 1.5.

Infelizmente só eu desenvolvo, e estou trabalhando em outros projetos o que acaba impossibilitando que eu mantenha um desenvolvimento constante.

Abraços
