### ISSUE TITLE
Notificação Area de trabalho

### ISSUE THREAD

**Issue by IsraelNSantos** [novosga/novosga#291]
Boa tarde, estou utilizando a versão do NovoSGA 1.5.0. No atendimento, quando habilito a notificação, não funciona. Já habilitei e mudei as configurações tanto no Google Chrome quanto no Mozilla Firefox.

**Comment by rogeriolino** [comment]
Qual versão dos navegadores?

**Comment by rogeriolino** [comment]
Fechando por falta de retonro.

**Comment by danill8rg** [comment]
Saudações estou com o mesmo problema estou utilizando o NovoSGA versão 1.5.0.  No atendimento quando habilito a notificação, não funciona, ao atualizar a pagina volta a aparecer o botão "! Habilitar notificação". Já adicionei permissão de javascript, permissão para pop, permissão cookie e não deu certo.
Estou utilizando o Opera  Versão: | 49.0.2725.47 e o Google Chrome Versão 63.0.3239.84 (Versão oficial) 64 bits. Observação no Mozila Firefox esta funcionando normalmente.
