### ISSUE TITLE
Requisitos de memória v2

### ISSUE THREAD

**Issue by hschiavo** [novosga/novosga#293]
Olá,
Qual o requisito de memória do PHP para instalar e executar o sistema?

grato,

**Comment by hschiavo** [comment]
executei esse comando abaixo.

`php composer.phar install`

Retorno...
Loading composer repositories with package information
Updating dependencies (including require-dev)

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 77 bytes) in phar:///home/.../novosga/composer.phar/src/Composer/DependencyResolver/Rule2Literals.php on line 53

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.

**Comment by rogeriolino** [comment]
Isso depende muito da versão de PHP que esteja utilizando. O fato é que o comando composer realmente usa muito mais memória do que uma simples requisição PHP.

Se você estiver tentando instalar em um servidor compartilhado, hospedagem, e não tem como alterar a configuração de memória do PHP, você tem duas alternativas:

1) Fazer a instalação local e enviar todo o código-fonte para o servidor incluindo o diretório vendor.

2) Fazer a instalação local, enviar apenas o arquivo `composer.lock` junto com o código-fonte (sem o vendor), e depois lá no servidor executar `composer install`.
