### ISSUE TITLE
Impressão via Google Cloud Print

### ISSUE THREAD

**Issue by gilbertogm85** [novosga/novosga#296]
Estou tentando implementar a impressão via Google Cloud Print, mas estou enfrentando alguns problemas.

no arquivo public/index.php tentei colocar a chamada:
        $resarray = $gcp->sendPrintToPrinterContent($printerid, "Printing Doc using Google Cloud Printing", "<b>Teste</b>", "text/html");

E imprime corretamente o teste. Quanto tento alterar para:
        $resarray = $gcp->sendPrintToPrinterContent($printerid, "Printing Doc using Google Cloud Printing", $template, "text/html");

Ele imprime o nome do arquivo: print.twig.html. Eu não estou muito familiarizado com o framework, mas preciso carregar o html no parametro $template.

Alguém sabe como posso fazer isso, ou alguma outra forma?

**Comment by rogeriolino** [comment]
@gilbertogm85 sugiro você utilizar o [fórum do projeto](http://forum.novosga.org/) para esse tipo de assunto e deixar aqui para tratar de bug e/ou funcionalidades do sistema.

Att.
