### ISSUE TITLE
Erro ao conectar o Painel-web ou Triagem-Touch

### ISSUE THREAD

**Issue by pablolira** [novosga/novosga#297]
Prezados, realizei todos os procedimentos descrito no manual aqui aplicado e também consegui subir as aplicações porém quando vou configurar o Painel WEB ou Triagem Touch apresentamos a mensagem: A URL informada não é válida. Favor tentar novamente.

Eu coloco o endereço ele não identifica e não deixa passar para validar. Alguém se deparou com tal problema?

**Comment by gilbertogm85** [comment]
Você está colocando a URL completa incluindo o http://?

Coloque o exemplo de como você está fazendo, assim fica mais fácil te ajudar. A URL deve ser a mesma que você utiliza para acessar o novo sga.

**Comment by pablolira** [comment]
Sim, estou colocando com o http:// juntamente o IP, coloquei inclusive um IP público também e um local para tentar acesso e mesmo assim não tenho acesso, estando um lado a lado do outro.

**Comment by pablolira** [comment]
Acredito então que a URL não pode ser somente a raiz ou seja a pasta onde encontra-se o SGA ?

**Comment by gilbertogm85** [comment]
Você tem que colocar o endereço de acesso completo,, ex:http://localhost/novosga/public ou caso seu servidor já esteja apontando para essa URL, deveria funcionar.

**Comment by pablolira** [comment]
Deu certo.

**Comment by pablolira** [comment]
Obrigado.
