### ISSUE TITLE
Senhas preferenciais não estão obedecendo ordem de prioridade

### ISSUE THREAD

**Issue by eduardomunizbarreto** [novosga/novosga#299]
Estou tendo problemas com as senhas preferenciais. As últimas senhas preferenciais tiradas além de irem para o final da fila estão ficando atrás das senhas sem prioridades.

**Comment by fielcomunista** [comment]
Eduardo, bom dia!
Gostaria de sugerir que você acompanhe o Fórum do NovoSGA em http://forum.novosga.org/, você encontrará muitas informações lá. Se utilizar a ferramenta de buscas com o termo prioridades você, certamente, encontrará a informação de que necessita.
Não sei se é o seu caso, mas as senhas preferenciais, por padrão, entram no fim da fila (há uma lei federal que é respeitada pelo sistema) e um algoritmo vai, de acordo com o tempo, levando a senha preferencial (com um peso maior) para o atendimento que a lei determina. Não é porque uma gestante, idoso, etc, chegou que quem está há mais de duas horas aguardando atendimento e até já se levantou para ir ao atendente deve voltar a sentar-se!!
Dá uma olhada no Fórum, não sou especialista nisso, mas utilizamos o sistema aqui e tem funcionado perfeitamente. Não há uma só reclamação quanto ao atendimento prioritário.
Abraços!

**Comment by rafael-neri** [comment]
@eduardomunizbarreto por padrão as senhas prioritárias tem um peso maior mas não quer dizer que entram no inicio da fila.

Eu precisei reconfigurar isso e foi bem simples.

Bastar criar um arquivo de configuração.

```php
<?php
// config/app.php
return [
    'queue' => [
        'ordering' => [
            [
                'exp'   => 'p.peso',
                'order' => 'DESC',
            ],
            [
                'exp'   => 'e.numeroSenha',
                'order' => 'ASC',
            ]
        ]
    ]
];
```
