### ISSUE TITLE
Escolha do serviço a ser atendido

### ISSUE THREAD

**Issue by elianetusset** [novosga/novosga#300]
Bom dia,

Por gentileza avaliar para a alteração a funcionalidade para que o usuário logado possa escolher o serviço a ser atendido após o login, caso o mesmo possua mais de que um serviço relacionado ao seu usuário.

Obrigada!

**Comment by rogeriolino** [comment]
Boa tarde,

A responsabilidade de definir o que cada atendente deve atender é do gestor/gerente, e não deve ficar a cargo do próprio atendente escolher o que quer atender.

Att.
