### ISSUE TITLE
Estatística - Hoje

### ISSUE THREAD

**Issue by elianetusset** [novosga/novosga#301]
Bom dia,

Gostaria que fosse avaliado a possibilidade de incluir a Unidade a ser escolhida ao clicar em Estatísticas - Hoje, visto que em determinadas organizações, o SGA de várias unidades podem estar sendo acopladas na mesma base de dados.

Obrigada!

**Comment by rogeriolino** [comment]
A vesão 1.x do Novo SGA não receberá mais suporte. E a partir da versão 2.0 o módulo de relatórios filtra os dados a partir da unidade atual do usuário.
