### ISSUE TITLE
Problemas na API

### ISSUE THREAD

**Issue by jppcel** [novosga/novosga#304]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| MySQL version    | 5.7
| PHP version      | 7.1
| Platform/OS      | Debian 9.0
| Novo SGA version | 2.0.0-RC2

A API está com problemas relativos à impressão da senha.

Ao acessar a rota /api/print/{id}/{hash} por POST(algo que seria melhor se fosse em GET, considerando o triagem-touch) ele dá o seguinte erro:
`Attempted to call an undefined method named "printTicket" of class "App\Controller\Api\TriagemController".`
O erro se dá no arquivo [src/Controller/Api/TriagemController.php#L44](https://github.com/novosga/novosga/blob/master/src/Controller/Api/TriagemController.php#L44) onde ele chama um método que não existe nessa classe, porém, ao analisar o arquivo que [está no repositório do módulo de Triagem: Controller/DefaultController.php#L74](https://github.com/novosga/triage-bundle/blob/master/Controller/DefaultController.php#L74), ele utiliza a triagem por parte do TicketService, ao invés da própria classe.
Eu estou fazendo as alterações necessárias para funcionar a triagem-touch, e irei fazer o pull request em breve, porém, isso está impossibilitando de finalizar as alterações.

**Comment by rogeriolino** [comment]
Alterei a rota para

GET /api/print/{id}

E o hash deve ser passado por querystring: `/api/print/{id}?hash={hash}`

Ou via cabeçalho `X-HASH` para maior segurança.
