### ISSUE TITLE
Relatórios e Gráficos com Erro

### ISSUE THREAD

**Issue by jppcel** [novosga/novosga#306]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| MySQL version    | 5.7
| PHP version      | 7.1 
| Platform/OS      | Debian 9.0
| Novo SGA version | 2.0.0-RC3

Relativo aos relatórios e gráficos.

Relatórios:

- Serviços Disponíveis - Unidade: Está retornando um erro 500.
- Serviços Executados: Mesmo havendo serviços executados no período selecionado, ele retorna como senão ouvesse.
![image](https://user-images.githubusercontent.com/3324772/39948539-d49df94e-554c-11e8-8be5-26800dcd26a1.png)
- Atendimentos Concluídos: Também acontece o mesmo dos Serviços Executados, mas também o título da primeira coluna não aparece como traduzido, está "label.ticket".
![image](https://user-images.githubusercontent.com/3324772/39948569-fac6655c-554c-11e8-8fb3-9cd633ccd8f8.png)
- Atendimentos em todos os status: Também ocorre o mesmo de Atendimentos Concluídos.
![image](https://user-images.githubusercontent.com/3324772/39948598-23aa2274-554d-11e8-88a8-7467efe564da.png)
- Tempos médios por Atendente: Temos diversos atendentes e já ouve atendimentos, e aparece assim:
![image](https://user-images.githubusercontent.com/3324772/39948628-4318665c-554d-11e8-822f-755d201654f4.png)
- Perfis: Aparece erro 500.

Gráficos:
- Atendimento por Status: Ele retorna como senão ouvesse atendimentos.
![image](https://user-images.githubusercontent.com/3324772/39948664-799764f8-554d-11e8-8d2a-d089572d5447.png)
- Atendimentos por Serviço: ele aparece um código que parece ser um js.
![image](https://user-images.githubusercontent.com/3324772/39948680-90c1c6be-554d-11e8-8d57-4f17b7b818b7.png)
- Tempo médio do atendimento: Ele retorna como senão ouvesse atendimentos.
![image](https://user-images.githubusercontent.com/3324772/39948692-9c3f414c-554d-11e8-9cd3-fe7f32917c29.png)

**Comment by rogeriolino** [comment]
Os dados não estão aparecendo porque está puxando apenas do histórico (tabela de histórico de atendimento, preenchida após reiniciar as senha).

Antes existia uma View com UNION das duas tabelas (atendimentos e historico_atendimentos).

Estou estudando uma forma de fazer isso pelo ORM (sem precisar escrever os SQL como antes), de forma que fique mais fácil portar para outros bancos.
