### ISSUE TITLE
Notificação API JS 

### ISSUE THREAD

**Issue by ThiagoViniski** [novosga/novosga#307]
Não sei se alguém aqui já teve ou está com esse problema.

No Google Chrome as notificação param após atualização do navegador. O motivo disso é que o API JS só funciona em **HTTP://** e o navegador após essas atualização exige que o API JS esteja para **HTTPS** ou seja mesmo quando você clica no botão para habilitar notificação a programação do navegador rejeita o pedido. O que quero saber é o seguinte.
**Alguém conseguiu resolver esse problema?**

**As versões mais nova do SGA estão estável?** 

**As notificações estão funcionando perfeitamente no Google Chrome?**

Desde já agradeço a  atenção e compreensão de todos.

**Comment by paulocuiaba** [comment]
Olá. Pelo que vi as discussões estão ocorrendo agora no https://discuss.novosga.org/ já inclui a sua sugestão/pergunta lá. 

https://discuss.novosga.org/d/86-https-no-sga-2-0

**Comment by ThiagoViniski** [comment]
Gratidão.

**Comment by rogeriolino** [comment]
O protocolo no qual a aplicação está rodando é de responsabilidade da infraestrutura, do servidor HTTP (Apache2, NGINX, IIS, etc).

Quem faz a instalação que configura se a mesma irá em HTTP plano ou com segurança (SSL).

**Apache2**
https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html

**NGINX**
https://nginx.org/en/docs/http/configuring_https_servers.html
