### ISSUE TITLE
Firebird e loja shop sga

### ISSUE THREAD

**Issue by oliveira01avantix** [novosga/novosga#309]
Caros

Esta rodando em firebird?

Referente a loja esta funcionando, pois estou tentando realizar compra de um thema e nao estou conseguindo, qualquer coisa entre em contato via email oliveira@avantix.com.br

**Comment by rogeriolino** [comment]
@oliveira01avantix não entedi. Explique melhor por favor.

**Comment by oliveira01avantix** [comment]
A nova versão ja contempla suporte a banco de dados Firebird, outro ponto estou tentando comprar plugins para a versão 1.5 no shop sga e não consigo finalizar o pedido, me informa erro.

 

 

De: Rogério Alencar Lino Filho [mailto:notifications@github.com] 
Enviada em: segunda-feira, 16 de julho de 2018 17:34
Para: novosga/novosga
Cc: oliveira01avantix; Mention
Assunto: Re: [novosga/novosga] Firebird e loja shop sga (#309)

 

@oliveira01avantix <https://github.com/oliveira01avantix>  não entedi. Explique melhor por favor.

**Comment by rogeriolino** [comment]
Não terá suporte para Firebird (pelo menos inicialmente).

Sobre a loja, me mande por email qual erro está dando.

Vou fechar essa issue.

**Comment by oliveira01avantix** [comment]
Segue abaixo

 



 

De: Rogério Alencar Lino Filho [mailto:notifications@github.com] 
Enviada em: segunda-feira, 16 de julho de 2018 18:50
Para: novosga/novosga
Cc: oliveira01avantix; Mention
Assunto: Re: [novosga/novosga] Firebird e loja shop sga (#309)

 

Não terá suporte para Firebird (pelo menos inicialmente).

Sobre a loja, me mande por email qual erro está dando.

Vou fechar essa issue.
