### ISSUE TITLE
Utilizar um algorítimo criptograficamente seguro para senha

### ISSUE THREAD

**Issue by CauanCabral** [novosga/novosga#31]
Hash simples baseado em MD5 e SHA1 são facilmente quebráveis com os equipamentos atuais.

Dois links que discutem bastante alterantivas:
- https://wiki.php.net/rfc/password_hash
- https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines#Password_Storage

Posso implementar uma das soluções na classe Security caso tenha interesse (substituindo o método atual).

Talvez seja interessante criar um mecanismo para fazer atualização das senhas atuais com MD5 para o novo formato.
##

**Comment by rogeriolino** [comment]
- [ ] Criar coluna "algoritmo" para guardar algoritmo utilizado no hash da senha. Atualmente usa MD5, então no script de migração do banco já deve iniciar a coluna com "md5".

- [ ] Criar interface PasswordProvider e suas especializações (ex Md5PasswordProvider)

- [ ] Criar factory do password provider para retornar a instância a partir do usuário

- [ ] Definir um novo algoritmo para armanezar as senhas e implementar o seu provider

- [ ] Utilizar novo provider ao criar novos usuário ou atualizar senha

**Comment by CauanCabral** [comment]
@rogeriolino estava dando uma olhada na situação do projeto depois de um bom tempo afastado e gostei bastante do que tem feito, parabéns.

Tenho algumas ideias para implementar essa issue, posso fazer uma proposição via PR?

 - Acho que não precisa da coluna com o algoritmo. Pelo tamanho da string de hash já podemos deduzir que é MD5 ou um formato moderno
 - Como a versão 2.0 é baseada no Symfony 3, que por sua vez tem dependencia no PHP 5.5, podemos usar as extensões nativas de password que foram implementadas e na época que abri essa issue não existiam ( http://php.net/manual/pt_BR/function.password-hash.php )
 - O restante do seu checklist eu estou de acordo, só faria transparente a migração de senha: sempre que um usuário fizer login e ainda tiver hash md5, o sistema detecta e faz um novo hash a partir da senha fornecida usando a nova implementação.

**Comment by rogeriolino** [comment]
Obrigado @CauanCabral .

Se você olhar a entidade usuário no branch v2.0 já está assim (algoritmo + salt): https://github.com/novosga/novosga/blob/v2.0/src/Novosga/Entity/Usuario.php

Por enquanto no security.yml só tem definido MD5, mas depois vou criar uma entrada para o MessageDigest do próprio Symfony:

https://github.com/novosga/novosga/blob/v2.0/app/config/security.yml

E por exemplo no security.yml:

```yml
encoders:
        ...
        bcrypt:
            algorithm: bcrypt
            cost: 15
```

Por fim estou pensando em detectar que o perfil do usuário é da versão antiga e levar o usuário para uma página para atualizar o perfil. Aí nesse caso poderia até adicionar o campo e-mail (que daria para utilizar para envio de alertas).
