### ISSUE TITLE
Alguem sabe algum manual para atualizar o Novo SGA da versão 1.5 para a 2.0.2???

### ISSUE THREAD

**Issue by leandrowaltz** [novosga/novosga#310]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| MySQL version    | x.y.z
| PHP version      | x.y.z
| Platform/OS      | Debian 9.0
| Novo SGA version | x.y.z

**Comment by rogeriolino** [comment]
Ainda não existe.

Um novo issue foi aberto para criação do script de migração #312, você pode acompanhar por lá.
