### ISSUE TITLE
Migração versão 1.5 para 2.0

### ISSUE THREAD

**Issue by rafaabrito** [novosga/novosga#312]
Criar Script de migração da versão 1.5 para a versao 2.0

**Comment by wendelmeloo** [comment]
Foi criado o script?

**Comment by rogeriolino** [comment]
ninguém criou

**Comment by JaumPOS** [comment]
Tem como atualizar a versão sem esse tal script?

**Comment by rogeriolino** [comment]
não, há alterações no banco de dados que precisam ser migradas.
