### ISSUE TITLE
[FEATURE REQUEST] Módulo de Pesquisa de Satisfação

### ISSUE THREAD

**Issue by suportecri1** [novosga/novosga#313]
Seria interessante ter um opção para classificar o atendimento.
Criar uma página que poderia ser apresentada em um tablet  com uma pergunta e algumas opções de respostas. 
Seria interessante também poder encadear perguntas, para possibilitar que a cada resposta dada uma nova pergunta seja apresentada ao cliente.

Outra opção seria cadastrar o email do usuário e ao fim do atendimento ser enviado uma mensagem solicitando ao usuário responder a pesquisa, redirecionando o usuário para a mesma página supracitada.
O link para a pesquisa poderia ser enviado via sms também!

**Comment by lamasbr** [comment]
Uma opção interessante seria também a opção de classificar o atendimento através de terminais de pesquisa de satisfação, como esse abaixo.

![image](https://user-images.githubusercontent.com/668513/46892161-d1ee0300-ce42-11e8-95e2-60b627e1d073.png)
