### ISSUE TITLE
[FEATURE REQUEST] Relatório de Produtividade

### ISSUE THREAD

**Issue by suportecri1** [novosga/novosga#314]
Do momento que a senha é retirada até o momento que é chamada no painel podemos ter uma métrica de tempo de espera.

Do momento que é chamada a senha até o momento que é iniciado o atendimento (ao clicar no botão), podemos ter uma métrica de tempo de deslocamento.

Do momento em que o atendente clica no botão para iniciar o atendimento até o momento que finaliza o atendimento, podemos ter uma métrica de tempo de atendimento.

Do momento que o atendente abre a tela de chamadas até o momento em que ele chama uma senha, podemos ter uma métrica de tempo de ociosidade. Inclusive podemos ter aqui alguma métrica de "ociosidade deliberada", quando mesmo havendo senhas para serem chamadas, o usuário não chamar.

Utilizando-se dessas métricas poder-se-ia gerar relatórios com dados de produtividade importantes para o gestor, visto que a ociosidade é uma casualidade que tem muito impacto na gestão! O tempo de deslocamento também seria uma ferramenta importante para observar discrepâncias e identificar atendentes que estejam tentando disfarçar sua ociosidade fazendo o cliente esperar dentro de um atendimento!

Essas são métricas que fazem toda a diferença para um gestor e que nem todo sistema de gerenciamento de filas possui (mesmo os comerciais).

**Comment by anahorn** [comment]
Atualmente sinto falta apenas de uma coluna no relatório de Atendimento em todos os Status que fornece o horário da retirada senha, só isso já resolve, o relatório está completo.
