### ISSUE TITLE
Não atualiza fila de senhas

### ISSUE THREAD

**Issue by luizboeri** [novosga/novosga#318]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| MySQL version    | docker ultima versão
| PHP version      | docker ultima versão
| Platform/OS      | Debian 9.0
| Novo SGA version | docker ultima versão

Quando é feita uma nova requisição pelo painel touch não está atualizando a lista de senhas para os atendentes sozinho, está precisando atualizar com F5 para aparecer.

**Comment by Projetos2** [comment]
Uma solução é adicionar a linha setInterval(app.update, 10000); no arquivos attendance-bundle/resources/public/js/script.js após app.init(atendimento)

`app.init(atendimento);
setInterval(app.update, 10000);

if (!local) {
    $('#dialog-local').modal('show');
}`
