### ISSUE TITLE
NovoSGA 2 LDAP Login

### ISSUE THREAD

**Issue by informaticavera** [novosga/novosga#319]
| Q                | A
| ---------------- | -----
| Bug report?      |no
| Feature request? | yes
| Novo SGA version | 2.0.3

**Comment by suportecri1** [comment]
seria bom mesmo!!!!

**Comment by rogeriolino** [comment]
A partir da versão 2.0, e adoção do Symfony como framework, ficou mais complicado fornecer essa funcionalidade por padrão.

Mas a própria documentação oficial do Symfony mostra como fazer essa integração:

https://symfony.com/doc/current/security/ldap.html

Quem sabe em uma versão futura o Novo SGA não volte com essa funcionalidade nativa.

**Comment by mitchbr91** [comment]
Boa tarde, pessoal.

Eu instalei o novo SGA na instituição onde trabalho (MP-BA) e estou tentando fazer a autenticação via AD. Gostaria de ajudar de alguém que efetivamente teve sucesso nisso. Já tentei diversas coisas baseadas na documentação oficial do Symfony, como sugerido, mas nada funciona. Além dois 2 arquivos config/packages/security.yaml e config/services.yaml, é preciso configurar mais alguma coisa? Segue o conteúdo do meu arquivo.

Arquivo services.yaml

`# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: '%env(LANGUAGE)%'
    version: '2.0.7'
    title: 'Novo SGA CE'

services:
    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -   host: intranet.mp.ba.br
                port: 389
                encryption: tls
                options:
                    protocol_version: 3
                    referrals: false    # default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services.
        autowire: true
        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.
        public: false
        bind:
            $rootDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Listener\SessionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 6 }

    App\Listener\AccessListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 7 }

    App\Listener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 700 }

    App\Listener\JsonExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1000 }

    App\Listener\ORM\DoctrineListener:
        tags:
            - { name: doctrine.event_subscriber }

    App\Service\TicketService:
        public: true

    App\Loader\RouterLoader:
        tags:
            - { name: routing.loader }

    App\Extensions\Doctrine\TablePrefix:
        arguments: [""]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: default }

    App\Extensions\Doctrine\SchemaViewIgnorer:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema, connection: default }

    # novosga core services
    Novosga\Service\:
        resource: '../vendor/novosga/core/Service'
        public: true

    Novosga\Event\EventDispatcherInterface: '@App\Service\EventDispatcher'

    Novosga\Infrastructure\StorageInterface:
        factory: 'App\Infrastructure\StorageFactory:createStorage'

    Novosga\Service\Configuration:
        $rootDir: '%kernel.project_dir%'
`
Arquivo security.yaml:

`security:
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12

        md5:
            algorithm: md5
            encode_as_base64: false
            iterations: 1

    providers:
         novosga_provider:
                entity:
                        class: Novosga\Entity\Usuario

         my_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: 'ou=Funcionarios,dc=intranet,dc=mp,dc=ba,dc=gov,dc=br'
                search_dn: 'cn=sisd.novosga,ou=Usuarios de sistema,dc=intranet,dc=mp,dc=ba,dc=gov,dc=br'
                search_password: 'senha'
                default_roles: ROLE_USER
                filter: '({uid_key}={username})'
                uid_key: 'sAMAccountName'


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
           pattern:    ^/api/token
           security:   false

        api:
           pattern:    ^/(api|\w+\.\w+/api)
           fos_oauth:  true
           stateless:  true
           anonymous:  false

        main:
            anonymous: true
            pattern: ^/
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
                dn_string: '{username}'
                provider: my_ldap
                login_path: /login
                check_path: /login_check
            guard:
               authenticators:
                  - App\Security\LoginAuthenticator
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/(api|\w+\.\w+/api), roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/login, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/admin, roles: [ ROLE_ADMIN ] }
        - { path: ^/,      roles: [ ROLE_USER ] }


    access_decision_manager:
        strategy: affirmative
`
Eu já consegui autenticação com o AD na instalação de outra aplicação. Logo, as informações estão corretas e seriam iguais as que pus nos arquivos diferenciando apenas o usuário e senha da aplicação para autenticação.

Ps: a mensagem de erro que estou tendo ao tentar autenticar é "usuário não encontrado"

Muito grato pela ajuda!!!

**Comment by guinuxbr** [comment]
Boa noite. Testa com outra OU que não tenha espaços no nome.

Em qua, 14 de ago de 2019 16:00, mitchbr91 <notifications@github.com>
escreveu:

**Comment by mitchbr91** [comment]
guinuxbr, tentei o que você sugeriu e não funcionou. Copiei os DNs direto do AD e continuo sem sucesso. 

Sobre o valor do atributo 'dn_string' do arquivo 'config/packages/security.yaml' já tentei diversos valores dentre eles:

'{username}'
'MP/username'
'{username},ou=Funcionarios,dc=intranet,dc=mp,dc=ba,dc=gov,dc=br'

Todos sem sucesso. Teria mais alguma coisa que poderia fazer? 

No arquivo 'config/services.yaml' para o valor do atributo 'host' usei apenas o nome da intranet: intranet.mp.ba.br que é resolvido pra 3 ips diferentes. Sobre esse atributo, ele precisa desse '-' mesmo na frente? Precisa colocar algo como ldap://intranet.mp.ba.br, ou como pus basta?

 -   host: intranet.mp.ba.br

**Comment by informaticavera** [comment]
Olá, estamos muito interessados ​​em experimentar a nova versão do novosga, você sabe se essa funcionalidade está implementada?

**Comment by mitchbr91** [comment]
Até agora não consegui sucesso na autenticação via AD. Na realidade, eu
meio que desisti. =/

Em qui, 12 de set de 2019 às 04:14, informaticavera <
notifications@github.com> escreveu:

**Comment by marcelfreitas** [comment]
Alguem conseguiu fazer essa integração?
