### ISSUE TITLE
Problemas com adição de usuário

### ISSUE THREAD

**Issue by jppcel** [novosga/novosga#321]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| MySQL version    | docker
| PHP version      | docker
| Platform/OS      | Debian 9.0
| Novo SGA version | 2.0.3

Estamos tendo um problema com os usuários administradores das unidades, nos quais criamos um perfil no qual estão inseridos com todas as permissões, mas ao tentarem acessar a página para criar um usuário, está dando erro 500, como na imagem.
![2018-10-10 1 2](https://user-images.githubusercontent.com/3324772/46751875-28680f80-cc92-11e8-9e1a-13de1cd0296e.png)

**Comment by rogeriolino** [comment]
Após atualização o problema foi resolvido?

**Comment by jppcel** [comment]
Bom dia,
A partir de qual versão está resolvida? 
Pois no momento estou com a 2.0.4 implementada devido a alguns problemas de lentidão e outros problemas junto ao Emissor de Senhas e ao Painel que estavam recorrentes quando implementamos a 2.0.7 e com isso retornamos a 2.0.4 que estava mais estável.

**Comment by rogeriolino** [comment]
Foi a partir da 2.0.4 mesmo. Você está com ela instalada e ainda tem o problema?

Olhei o histórico de comits não vi algo que pudesse gerar lentidão.
