### ISSUE TITLE
Erro Banco de Dados/ Ausência de Lotação

### ISSUE THREAD

**Issue by coutogilson** [novosga/novosga#322]
Erro Banco de Dados:
Ao acessar o PhpMyAdmin é reportado o seguinte erro. Não consigo criar Usuário por falta de Lotação.

> Warning in ./libraries/sql.lib.php#601
>  count(): Parameter must be an array or an object that implements Countable
> 
> Backtrace
> 
> ./libraries/sql.lib.php#2038: PMA_isRememberSortingOrder(array)
> ./libraries/sql.lib.php#1984: PMA_executeQueryAndGetQueryResponse(
> array,
> boolean true,
> string 'novosgadb',
> string 'agendamentos',
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string '',
> string './themes/pmahomme/img/',
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `agendamentos`',
> NULL,
> NULL,
> )
> ./sql.php#216: PMA_executeQueryAndSendQueryResponse(
> array,
> boolean true,
> string 'novosgadb',
> string 'agendamentos',
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string '',
> string './themes/pmahomme/img/',
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `agendamentos`',
> NULL,
> NULL,
> )

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| MySQL version    | 5.7.23
| PHP version      | 7.2
| Platform/OS      | Ubuntu 16.04
| Novo SGA version | 2.0.3

**Comment by gilsonfernando** [comment]
Estou com o mesmo problema, alguém conseguiu resolver?

**Comment by dtgfranca** [comment]
mesmo erro. Alguém sabe se a versão anterior tem esse  mesmo problema?

**Comment by coutogilson** [comment]
Reinstalei o NovoSGA na versão 2.0.7 (atenção quando rodar o Composer). Agora instalou, mas ainda não consigo inserir usuários ou criar lotações.
Ao tentar configurar a senha dá uma mensagem The server returned a "405 Method Not Allowed".
