### ISSUE TITLE
Chamar uma senha diretamente

### ISSUE THREAD

**Issue by suportecri1** [novosga/novosga#323]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| MySQL version    | 5.7
| Platform/OS      | Docker
| Novo SGA version | 2.1

Cria um campo booleano em novosga.settings para permitir (ou não) que um usuário chame a senha diretamente. Uma vez ativada a configuração, o usuário poderia clicar diretamente na senha em questão (na fila do novosga.attendance), onde haveria um botão para chamar a senha diretamente, ignorando sua posição na fila!

**Comment by vicsanjinez** [comment]
I need this feature too

**Comment by anahorn** [comment]
Também preciso.

**Comment by anahorn** [comment]
Também preciso.

**Comment by computocell** [comment]
Desenvolvi algo parecido no SGA 1.5

**Comment by ygodesignertk830** [comment]
> Desenvolvi algo parecido no SGA 1.5

Oi amigo teria como disponibilizar ? eu estou precisando disso, por favor, minha versão é 1.5 meu email: [designertk238@gmail.com](mailto:designertk238@gmail.com), te agradeceria muito.
