### ISSUE TITLE
Prioridade - Tem como mudar no código para ficar uma prioridade e uma não prioridade?

### ISSUE THREAD

**Issue by azzarodev** [novosga/novosga#335]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| MySQL version    | x.y.z
| PHP version      | x.y.z
| Platform/OS      | Debian 9.0
| Novo SGA version | x.y.z

Olá Senhores,

Estou tendo dificuldade em relação a prioridade. Meu caso o sistema precisa chamar uma prioridade e uma não prioridade. Se alguém tiver essa informação, fico grato.

**Comment by jppcel** [comment]
deixe-me ver se eu entendi:
no caso é para fazer meio que chamar uma senha para atendimento da fila normal, depois de atender este chamar uma de prioridade e assim vai?
se for assim, tem uma forma que utilizam-se no trabalho, apesar de eu não achar bem correto: quando precisa fazer a mudança para atender uma prioridade ou então uma normal, é alterado a fila que o atendente está a atender, ou seja, quando é necessário chamar apenas os normais, o atendente configura para pegar a fila do convencional, e quando é para atender os prioritários, ele muda a fila para a normal, que chama os prioritários primeiro dos convencionais.

**Comment by azzarodev** [comment]
Essa sua ideia é boa. Acho que poderíamos fazer essa solução. 
Mas tenho alguns problemas que vou relatar mais abaixo.
O Fluxo da fila funciona dessa forma:
O paciente chega e recebe a senha para ser atendido, antes de ser atendido pelo médico ele passa por uma habilitação, essa habilitação é uma "vistoria" para saber ele o paciente trouxe toda documentação para ser atendido, logo após o atendente que fez a habilitação encaminha a senha para o médico correspondente, cada paciente tem um médico específico, não podendo ser atendido por outro médico.
E quando os médicos vão chegando, vão chamando os que já foram habilitados, só que essa espera é grande, as vezes o paciente é habilitado até duas horas antes de o médico chamar, por isso que quando o médico começa a chamar a fila dele, todas as prioridades são chamadas primeiro que os não prioridades e com isso gera uma confusão terrível. Por isso que pensei em trabalhar com todos os serviços chamando de forma automática um prioridade e um não prioridade, pois não teria problemas.

**Comment by azzarodev** [comment]
O nível dos operadores do sistema não é alto, a maioria já tem mais de 55 anos e com isso gera um enorme desconforto em ficar passando informações que eles devem alterar algumas coisas no sistema. A maioria é inseguro e não tem muito contato com computadores.
