### ISSUE TITLE
Erro de chave estrangeira ao reiniciar senhas

### ISSUE THREAD

**Issue by lcspereira** [novosga/novosga#339]
Ao reiniciar as senhas, ocorre um erro de chave estrangeira, conforme o print abaixo:

![image](https://user-images.githubusercontent.com/4412051/64276315-04529400-cf1e-11e9-993c-056fcf5f8e18.png)

Pude verificar que o autoincremento da tabela atendimentos voltou à 1, conforme já havia acontecido anteriormente, de maneira aleatória.

Notei que há uma issue semelhante à este problema (https://github.com/novosga/novosga/issues/202), no entanto, a estrutura do banco de dados está bem diferente nessa versão para aplicar a solução mencionada.

Para solucionar o problema, foi buscado o último ID que foi inserido na tabela historico_atendimentos:

`SELECT MAX(id) FROM historico_atendimentos;`

Após, com este valor, foram corrigidos os IDs nas tabelas atendimentos e atendimentos_codificados:

`UPDATE atendimentos SET id = <max_historico_id> + id;
UPDATE atendimentos_codificados SET atendimento_id = <max_historico_id> + atendimento_id;`

Assim foi possível reiniciar as senhas pelo sistema. Depois de efetuar a reinicialização das senhas, foi verificado novamente o último ID da tabela histórico_atendimentos e corrigida a configuração de autoincrement da tabela atendimentos (último ID da tabela historico_atendimentos + 1).

Como mencionado anteriormente, já é a segunda vez que é necessário efetuar este procedimento.

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| MySQL version    | 5.7.27-0ubuntu0.18.04.1
| PHP version      | PHP 7.2.19-0ubuntu0.18.04.2
| Platform/OS      | Ubuntu 18.04.2 LTS
| Novo SGA version | 2.0.7

Grato pela atenção.

**Comment by mtbrandao** [comment]
Também estou com esse problema.

**Comment by lcspereira** [comment]
Percebe-se que para reproduzir o problema, é preciso que se tenha reiniciado as senhas (tabela atendimentos vazia) e o banco seja reiniciado. Conforme documentação do MySQL, o autoincrement é armazenado em memória, e quando o MySQL é reiniciado, o mesmo seta o autoincrement de acordo com o último valor do campo autoincrement na tabela. Como não há registros, o mesmo volta o autoincrement para 1, o que ocasiona o erro no próximo reset das senhas.

Algo que poderia solucionar é alterar a unit do MySQL, e configurar um script de pré-execução para executar o seguinte comando no mesmo:

ALTER TABLE atendimentos AUTO_INCREMENT = ultimo_valor_tabela_historico_atendimentos;

Feito isso, não deve ocorrer mais o problema.

No entanto, creio que os desenvolvedores podem prover uma solução mais elegante para o problema.
Ressalto que o problema ocorre também na versão 2.0.8.

**Comment by edilvolima** [comment]
O problema ainda persiste na versão 2.0.9. 

Consigo resolver usando a estratégia do amigo @lcspereira mas é aleatório as ocasiões que acontece. Já monitores por dias e funciona tudo normal... porém quando menos espera, o erro aparece novamente.

**Comment by ymgp01** [comment]
@rogeriolino Rogério, porque wontfix? Significa que isso nao pode ser solucionado de forma alguma, dentro do código / criando algo (como uma verificação/correção) dentro do proprio mysql??? @lcspereira @edilvolima @mtbrandao Alguma sugestão?

**Comment by mtbrandao** [comment]
@ymgp01 Varios os issues foram fechados com wontfix no dia 5 de junho.
Entendi que o projeto foi abandonado.

**Comment by rogeriolino** [comment]
@ymgp01 `wontfix` porque isso não será resolvido via código. É um comportamento do banco de dados e que há formas de contornar isso que já foram discutidas.

@mtbrandao versões antigas não receberão mais suporte, pelo menos de minha parte, e como praticamente apenas eu suportava essas versões, pode-ser dizer que foram descontinuadas.

Eu pretendo reescrever uma versão 3.0 do zero, fornecendo API para todas as ações de forma que seja possível implementar aplicativos a parte para cada funcionalidade (atendimento, monitoramento, triagem e painel). Infelizmente não tenho um cronograma para isso porque estou envolvidos com outras atividades.
