### ISSUE TITLE
Erro reset automático senha v2.0.8 - Banco Postgres

### ISSUE THREAD

**Issue by rarandrade** [novosga/novosga#341]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Postgres version    | 9.6
| PHP version      | 7.3
| Platform/OS      | Debian 9.0
| Novo SGA version |2.0.8

Ao executar o comando de reset automático da senha pelo Shell apresenta seguinte msg

/var/www/html/novosga/bin/console novosga:reset

In AbstractMySQLDriver.php line 106:

An exception occurred in driver: could not find driver

In PDOConnection.php line 31:

could not find driver

In PDOConnection.php line 27:

could not find driver

novosga:reset [-s|--seguro] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<unidade>].

Creio que esse erro seja devido ao drive de conexão do banco de dados visto que eu estou utilizando o Postgres ao invés do MySQL

**Comment by rogeriolino** [comment]
o sistema está tentando utilizar o MySQL, provavelmente a URL de conexão está errada.
