### ISSUE TITLE
Invalid AJAX response

### ISSUE THREAD

**Issue by GabrielBN123** [novosga/novosga#356]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Novo SGA version | 2.0

Ao tentar exibir o erro de triagem, ao tentar redirecionar após preencher todos os dados ainda aparece esse erro "Invalid AJAX response" mas ele redireciona, sabem me dizer onde consigo resolver isso?

**Comment by viniciuslimax10** [comment]
Conseguiu resolver?
