### ISSUE TITLE
Senhas se Repetindo em um Padrão Aleatório

### ISSUE THREAD

**Issue by NaskIII** [novosga/novosga#367]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| PostgreSQL version    | 8.3.14
| PHP version      | 5.2.6
| Platform/OS      | Debian 5.0.8
| SGA version | 1.1.0

Olá, Bom Dia.

Me chamo Raphael e sou funcionário da SPPREV que está alocada na Secretaria da Fazenda.

Nós aqui da Secretaria da Fazenda (SEFAZ), utilizamos o SGA desde 2009, onde desde então nunca apresentou problemas. Porém a partir do dia 21 de Dezembro de 2022, as senhas geradas pela aplicação estão se repetindo em um padrão aleatório de acontecimentos.

Em um momento a senha pode ir do 24 para a senha de número 3, e esse processo se repete fazendo com que as senhas nunca cheguem em um número maior que 30. 

Nos registros do banco temos diversas senhas iguais. Temos sete senhas 2, quatro senhas 4 e assim por diante. Além disso, toda vez que uma senha se repete o número da senha é reiniciado, porém o contador de senhas continua funcionando. Então podemos estar na senha 12 mas o contador de senhas nos mostra que já geramos 40 senhas.

Abaixo um exemplo das senhas repetidas:

![image](https://user-images.githubusercontent.com/33010870/209821127-fea6e59a-640d-49cb-980a-f65897faaf92.png)

Um comportamento observado é que se as senhas forem geradas em massa (40 senhas em sequencia), nenhum número se repete. Porém se existe um gap maior que 2 minutos entre uma senha e outra, as senhas já começam a se repetir.

De nossa parte não houve nenhuma modificação nem de máquinas nem de servidor. A aplicação também não foi modificada nem desconfigurada.

Espero que possa nos ajudar,

Obrigado.

Raphael Nascimento.

**Comment by rogeriolino** [comment]
Olá Rafael, primeiro eu recomendo atualizar sua versão do SGA para 1.5.1. Se o problema continuar tente olhar o log do banco de dados para ver como as consultas estão sendo executadas:
https://github.com/novosga/novosga/blob/v1.1.0/src/Novosga/Business/AtendimentoBusiness.php#L244-L247

**Comment by NaskIII** [comment]
Bom, magicamente o problema se corrigiu. Analisamos tudo o que foi possível aqui mas absolutamente ninguém tem a menor ideia do que ocorreu.

De qualquer forma, estamos preparado um novo ambiente para utilizar a ultima versão do SGA. 

Obrigado.
