### ISSUE TITLE
Erro na instalação do SGA 2.1 via composer

### ISSUE THREAD

**Issue by dollyzn** [novosga/novosga#368]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| MySQL version    | 5.7.40
| PHP version      | 8.0
| Platform/OS      | Ubuntu 22
| Novo SGA version | 2.1

Boa tarde, estava realizando a instalação do projeto via composer em um ubuntu server e me deparei com com um erro na hora de fazer o download do symfony/flex, de acordo com a documentação oficial desta lib a versão 1.3 utilizada no projeto esta "descontinuada" e o servidor que eles disponibilizavam para download dos arquivos foi desligado. Pretende atualizar o projeto para uma versão mais atual dessa lib?
![Captura de tela 2023-01-13 124846](https://user-images.githubusercontent.com/66445721/212361296-b998ac03-47eb-423c-9bd0-a690d1a033d3.png)

**Comment by dollyzn** [comment]
d

**Comment by cicerosz** [comment]
Bom dia meu amigo, quando cadastro uma conexão no status fica com o icone rodando e percebi que dá erro nesse servço:

websocket.js:203 WebSocket connection to 'ws://whaticket.api.ppac.cro.sap/socket.io/?EIO=4&transport=websocket&sid=q_BU0i4VdcFZq55AAAAJ' failed: WebSocket is closed before the connection is established.

Se por me ajudar agradeço!!!
