### ISSUE TITLE
AdminController - limparAtendimentos

### ISSUE THREAD

**Issue by lupainformatica** [novosga/novosga#372]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Novo SGA version | 2.1

```
$service->limparDados(); // Este método espera uma Unidade como parãmetro, porém está sendo chamado vazio
```
![image](https://github.com/novosga/novosga/assets/67587830/3061da85-0118-4247-9756-d18328207149)

**Comment by rogeriolino** [comment]
Resolvido na versão 2.1.3 (https://github.com/novosga/novosga/issues/395)

https://github.com/novosga/novosga/releases/tag/v2.1.3
