### ISSUE TITLE
Atualização de Relatório

### ISSUE THREAD

**Issue by caiodanc** [novosga/novosga#378]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| MySQL version    | mysql  Ver 15.1 Distrib 10.11.6-MariaDB
| PHP version      | 7.4
| Platform/OS      | Debian 12.4
| Novo SGA version | 2.0.9

Gostaria de sugerir / pedir uma melhoria nos dois relatórios abaixo:

- Atendimento Concluídos
- Atendimentos em todos os status

Criar uma coluna **CHEGADA** com seu respectivo horário nos relatórios citados anteriormente. 

Sendo assim possível a visualização desta informação em qualquer data selecionada no filtro.  

Muito obrigado!

**Comment by rogeriolino** [comment]
Essa alteração estará disponível na versão 2.2
