### ISSUE TITLE
Criação de arquivo CONTRIBUTING.md

### ISSUE THREAD

**Issue by vitormattos** [novosga/novosga#380]
O arquivo CONTRIBUTING.md contém instruções sobre como uma nova pessoa pode contribuir para o projeto e isto pode ser de diversas formas porém é preciso que as pessoas saibam como.

Este site explica um pouco como criar um CONTRIBUTING.md
https://contributing.md/

Seja livre para contribuir, faça já um fork do projeto e mande sua contribuição. Com o tempo vamos aprimorando este arquivo.

**Comment by rogeriolino** [comment]
Criada página contributing na documentação https://novosga.org/docs/#/2.1/contributing
e adicionado link para a mesma no README
