### ISSUE TITLE
Página 'Monitor' resgatando prioridade excluída da página 'Prioridades'

### ISSUE THREAD

**Issue by ghost** [novosga/novosga#394]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Novo SGA version | 2.1.2
| Database version | MySQL 5.7/PostgreSQL 15
| Platform/OS      | Linux/Docker

O bug aparece ao cadastrar uma Prioridade em /admin/prioridades/ e excluir.
Depois acesse o Monitor /novosga.monitor/, clique em uma senha > Transferir / Alterar Senha > Nova Prioridade.
**A prioridade excluída estará sendo listada.**

![Tela Monitor](https://github.com/user-attachments/assets/49769ff8-bdc8-42f1-a88a-65e00acfe15c)
![Tela Prioridades](https://github.com/user-attachments/assets/ca1e2004-b5a9-4b17-a99b-e424c555f021)

**Comment by lhfc93** [comment]
Por algum motivo não saiu o que digitei. Segue:
O bug aparece ao cadastrar uma Prioridade em **/admin/prioridades/** e excluir. 
Depois acesse o Monitor **/novosga.monitor/**, clique em uma senha > Transferir / Alterar Senha > Nova Prioridade.
**A prioridade excluída estará sendo listada**.

**Comment by rogeriolino** [comment]
Resolvido na v2.1.6: https://github.com/novosga/novosga/releases/tag/v2.1.6

**Comment by rogeriolino** [comment]
Resolvido no branch v2.2
