### ISSUE TITLE
Mercure key

### ISSUE THREAD

**Issue by fernandogiacomino** [novosga/novosga#414]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Novo SGA version | 2.1.5
| PHP version      | x.y.z
| Database version | MySQL 5.7
| Platform/OS      | Linux

Tal como comenté en Discuss, tengo una instalación nueva con docker compose, todo se instaló correctamente y funcionaba bien excepto la comunicación con Mercure, que daba un error de autenticación. 

Por un lado, quitaría el comentario que indica modificar MERCURE_PUBLIC_URL de aucerdo al nombre del host, basta con dejarlo con el nombre del contenedor (mercure), tal como está en el modelo:
      MERCURE_PUBLIC_URL: "http://mercure:3000/.well-known/mercure"
      MERCURE_CONSUMER_URL: "http://127.0.0.1:3000/.well-known/mercure"

Como bug el problema es
"# default publish key, must be changed"
MERCURE_PUBLISHER_JWT_KEY: "!ChangeMe!"

Dejándolo como está en el modelo, funciona bien. Si la cambias entonces ya no se autentica con Mercure.

**Comment by rogeriolino** [comment]
~A secret deve ser a mesma tanto no novosga quanto no mercure: https://mercure.rocks/docs/hub/config~

Edit: Essa documentação está atualizada e não é compatível com a versão antiga do Mercure-Bundle (que está sendo utilizada).

**Comment by rogeriolino** [comment]
@fernandogiacomino atualizei a documentação incluindo a variável de ambiente que estava oculta: `MERCURE_JWT_TOKEN`.

E adicionei exemplo de como gerar outro token JWT no fórum: https://discuss.novosga.org/d/721-problema-com-mercure/14
