### ISSUE TITLE
Visualização de Usuários

### ISSUE THREAD

**Issue by JoranFreire** [novosga/novosga#42]
Um usuário que tem permissão ao módulo, mas que não é do grupo Raiz(enfim, o grupo primário) não deveria poder visualizar usuários de outras unidades diversas da qual o usuário pertence, ou seja, essa visualização geral caberia apenas aos Usuários do Grupo raiz.
##

**Comment by rogeriolino** [comment]
Módulo de usuário agora filtra pela unidade atual do usuário.
