### ISSUE TITLE
Triagem duplicada 

### ISSUE THREAD

**Issue by ghost** [novosga/novosga#420]
| Q                                     | A
| ---------------------------| -----
| Bug report?                     |  yes
| Feature request?             | no
| Novo SGA version           |  2.1.7
| PHP version                     | 8.1.2
| Database version             | MySQL 5.7
| Platform/OS                    | Linux/Docker

## Apresentação do Erro
https://github.com/user-attachments/assets/84ea5777-b1e7-413e-805f-04d0051e658e

## Problema
O sistema exibe a triagem, de um agendamento externo, duplicada na interface de atendimento /novosga.attendance/

## Como reproduzir
1. Gere um agendamento via euagendei.online
2. Gere a senha desse agendamento na triagem
3. Confira a triagem duplicada na interface de atendimento

**Comment by rogeriolino** [comment]
@lhfc93 obrigado por reportar o problema, e de forma tão detalhada. Acredito que o problema seja o Mangati Triagem que está disparando mais de uma requisição. Acabei de fazer uma atualização nele, por favor verifique se o problema continua.

**Comment by ghost** [comment]
@rogeriolino Problema corrigido. Obrigado mais uma vez.
