### ISSUE TITLE
Peso por serviço

### ISSUE THREAD

**Issue by alnetosilva** [novosga/novosga#46]
Caros,
Na comunidade do sga livre tem uma postagem que o administrador pode relacionar o serviço com o usuário e determinar um peso para que o usuário possa atender a todos os tipos de serviços, mais possa direcionar seu foco a um tipo de atendimento. caso não haja esse tipo de atendimento ele continua atendendo os outros. Como posso inserir essa funcionalidade no sistema? pois hoje quando crio um usuário no sistema consigo inserir o serviço que ele vai atender. mais não consigo determinar um peso a sua fila!
Grato!

**Comment by rogeriolino** [comment]
A partir da versão 1.5.0 será possível definir o valor do peso do serviço na unidade.

Ficando, depois, a cargo do administrador do sistema definir a ordem da fila através do arquivo de configuração ```config/app.php```.

**Comment by alnetosilva** [comment]
Testei o novosga v1.5.0 e o peso por unidade atende, mas ainda não é suficiente. Acho que la no relacionamento usuario-unidade-servico deveria ter um peso também. Por exemplo, na criação de um ambiente onde o joão e a maria podem atender todos os serviços mas preferencialmente serviço A pois eles são mais rápidos neste tipo de atendimento e o josé e pedrinho atendem preferencialmente servico B pelo mesmo motivo. No entanto, ao selecionar apenas o melhor serviço para o usuario ele simplismente não vai ter fila quando não houver mais aquele serviço, sendo que ele poderia continuar produtivo.
