### ISSUE TITLE
Relatório de tempo médio por atendente

### ISSUE THREAD

**Issue by rogeriolino** [novosga/novosga#64]
Criar relatório com o tempo médio de cada atendente (por período):
- Atendente
- Total de atendimentos
- TMD
- TME
- TMA
- Tempo total

**Comment by lzuhuo** [comment]
Teria como incluir um filtro por unidade? Ou por atendente, pois mistura todos os atendentes de todas as unidades, e a gestora as vezes só quer saber da dela. Obrigado.
